In [4]:
import numpy as np
import pandas as pd

In [69]:
df=pd.read_csv("data.csv")
df.head(10)

,Unnamed: 0,Country,Continent,Production (Tons),Production per Person (Kg),Acreage (Hectare),Yield (Kg / Hectare)
0,0,Brazil,South America,768.678.382,"3.668,531",10.226.205,"75.167,5"
1,1,India,Asia,348.448.000,260721,4.950.000,"70.393,5"
2,2,China,Asia,123.059.739,88287,1.675.215,"73.459,1"
3,3,Thailand,Asia,87.468.496,"1.264,303",1.336.575,"65.442,2"
4,4,Pakistan,Asia,65.450.704,324219,1.130.820,57.879
5,5,Mexico,North America,56.446.821,452524,781.054,72.27
6,6,Colombia,South America,36.951.213,740075,416.626,"88.691,5"
7,7,Australia,Oceania,34.403.004,"1.373,406",447.204,"76.929,1"
8,8,Guatemala,North America,33.533.403,"1.938,114",259.85,"129.049,3"
9,9,United States of America,North America,29.926.210,91304,370.53,80.766

In [ ]:
df['Production (Tons)'].describe()
# shown as a categorical val but is numerical ... converting to numeric type
# the type of all the numerical columns are object type therefore need to be converted

count             103
unique            103
top       768.678.382
freq                1
Name: Production (Tons), dtype: object

In [ ]:
# Removing '.' and converting ',' to '.' for all the columns
# Converting them to int or float type as required by the problem 
df["Production (Tons)"] = (
    df["Production (Tons)"]
    .astype(str)
    .str.replace(r"\.", "", regex=True)
    .astype("int64")
    
)
df["Production per Person (Kg)"]=(
    df["Production per Person (Kg)"].astype(str)
    .str.replace(r"\.","",regex=True)
    .str.replace(r"\,",".",regex=True)
    .astype("float64")
)
df["Acreage (Hectare)"]=(
    df["Acreage (Hectare)"].astype(str)
    .str.replace(r"\.","",regex=True)
    .str.replace(r"\,",".",regex=True)
    .astype("float32")
)
df["Yield (Kg / Hectare)"]=(
    df["Yield (Kg / Hectare)"].astype(str)
    .str.replace(r"\.","",regex=True)
    .str.replace(r"\,",".",regex=True)
    .astype("float32")
)

0      768678382
1      348448000
2      123059739
3       87468496
4       65450704
         ...
98            97
99            53
100           50
101           12
102            1
Name: Production (Tons), Length: 103, dtype: int64

In [ ]:
#Not contributing to learning thereby removing it
del df["Unnamed: 0"]

,Country,Continent,Production (Tons),Production per Person (Kg),Acreage (Hectare),Yield (Kg / Hectare)
0,Brazil,South America,768678382,3668.531,10226205.0,75167.500000
1,India,Asia,348448000,260721.000,4950000.0,70393.500000
2,China,Asia,123059739,88287.000,1675215.0,73459.101562
3,Thailand,Asia,87468496,1264.303,1336575.0,65442.199219
4,Pakistan,Asia,65450704,324219.000,1130820.0,57879.000000
...,...,...,...,...,...,...
98,Lebanon,Asia,97,16.000,3.0,28386.400391
99,Djibouti,Africa,53,51.000,NaN,NaN
100,Singapore,Asia,50,9.000,2.0,25.000000
101,Samoa,Oceania,12,6.000,1.0,11949.799805
102,Syria,Asia,1,0.000,0.0,83034.203125

0        3668.531
1      260721.000
2       88287.000
3        1264.303
4      324219.000
          ...
98         16.000
99         51.000
100         9.000
101         6.000
102         0.000
Name: Production per Person (Kg), Length: 103, dtype: float64